name = "Muhammad Shamim's personal website"
license = "MIT"
description = "A high performance and mobile fast personal portfolio and blog."
homepage = "https://github.com/xeinshamim/muhammadshamim.com"
demosite = "https://xeinshamim.netlify.app"
tags = ["Responsive","Blog", "Portfolio", "Personal"]
min_version = "0.9"

[author]
  name = "Muhammad Shamim"
  homepage = "https://www.linkedin.com/in/xeinshamim/"
